plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
theme: jekyll-theme-minimal
title: "7RedViolin Blog"
description: DFIR Thoughts & CTF Writeups

paginate: 10
paginate_path: "/:num/"